name: netflix_2
description: "A new Flutter project."

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  background_icon: "#000000"
  image_path: "assets/images/symbol.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: "assets/images/symbol.png"
  android_12:
    image: "assets/images/symbol.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


  # fonts:
  #   - family: Calistoga
  #     fonts:
  #       - asset: fonts/Calistoga-Regular.ttf
  #         weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
